# Generated by Django 2.1 on 2019-03-19 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0003_auto_20190319_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normdock',
            old_name='cateory',
            new_name='category',
        ),
    ]
