# Generated by Django 2.1 on 2019-03-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0004_auto_20190319_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='normdock',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
