# Generated by Django 2.1 on 2019-03-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norms', '0006_auto_20190329_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normdock',
            name='name_code',
            field=models.CharField(max_length=96),
        ),
    ]
