# Generated by Django 2.1 on 2019-03-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('index_name', models.CharField(max_length=500)),
                ('scores', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Критерій',
                'verbose_name_plural': 'Критерії',
                'ordering': ['id'],
            },
        ),
    ]
