# Generated by Django 2.1 on 2019-03-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='is_main',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
