# Generated by Django 2.1 on 2019-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_auto_20190324_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
