# Generated by Django 2.1 on 2019-03-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_auto_20190324_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteria',
            name='scores',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
