# Generated by Django 2.1 on 2019-03-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0005_auto_20190324_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='criteria',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
