# Generated by Django 2.1 on 2019-03-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_searchrequest_total_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequest',
            name='updated',
        ),
    ]
