# Generated by Django 2.1 on 2019-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_searchrequest_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequest',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
