# Generated by Django 2.1 on 2019-03-12 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervchapter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='supervposition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
