# Generated by Django 2.1 on 2019-03-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laws', '0004_auto_20190314_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objecttype',
            name='description',
        ),
        migrations.AddField(
            model_name='objecttype',
            name='descr_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='descr_name',
            field=models.TextField(blank=True, default=None, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='law_chapter',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='objecttype',
            name='law_title',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
