# Generated by Django 2.1 on 2019-03-17 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField()),
                ('name', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('sum', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Критерій',
                'verbose_name_plural': 'Критерії',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='Indexes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_name', models.CharField(max_length=500)),
                ('scores', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Показник ',
                'verbose_name_plural': 'Показники',
                'ordering': ['-index_name'],
            },
        ),
        migrations.AddField(
            model_name='criteria',
            name='indexes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Indexes'),
        ),
    ]
