# Generated by Django 2.1 on 2019-03-17 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteria',
            options={'ordering': ['pub_date'], 'verbose_name': 'Критерій', 'verbose_name_plural': 'Критерії'},
        ),
    ]
