# Generated by Django 2.1 on 2019-03-17 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20190317_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criteria',
            name='indexes',
        ),
        migrations.AddField(
            model_name='indexes',
            name='criteria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='calc.Criteria'),
        ),
    ]
